# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vivado/projet_led_spi/led_start/led_start.srcs/sources_1/bd/led_btn/ip/led_btn_ila_0_1/led_btn_ila_0_1.xci
# IP: The module: 'led_btn_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/projet_led_spi/led_start/led_start.gen/sources_1/bd/led_btn/ip/led_btn_ila_0_1/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_btn_ila_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado/projet_led_spi/led_start/led_start.gen/sources_1/bd/led_btn/ip/led_btn_ila_0_1/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_btn_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado/projet_led_spi/led_start/led_start.gen/sources_1/bd/led_btn/ip/led_btn_ila_0_1/led_btn_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_btn_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Vivado/projet_led_spi/led_start/led_start.srcs/sources_1/bd/led_btn/ip/led_btn_ila_0_1/led_btn_ila_0_1.xci
# IP: The module: 'led_btn_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/projet_led_spi/led_start/led_start.gen/sources_1/bd/led_btn/ip/led_btn_ila_0_1/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_btn_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado/projet_led_spi/led_start/led_start.gen/sources_1/bd/led_btn/ip/led_btn_ila_0_1/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_btn_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado/projet_led_spi/led_start/led_start.gen/sources_1/bd/led_btn/ip/led_btn_ila_0_1/led_btn_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'led_btn_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
