# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/led.xdc

# Block Designs: bd/led_btn/led_btn.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_btn || ORIG_REF_NAME==led_btn} -quiet] -quiet

# IP: bd/led_btn/ip/led_btn_processing_system7_0_0/led_btn_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_btn_processing_system7_0_0 || ORIG_REF_NAME==led_btn_processing_system7_0_0} -quiet] -quiet

# IP: bd/led_btn/ip/led_btn_rst_ps7_0_100M_0/led_btn_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_btn_rst_ps7_0_100M_0 || ORIG_REF_NAME==led_btn_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/led_btn/ip/led_btn_xlslice_0_0/led_btn_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_btn_xlslice_0_0 || ORIG_REF_NAME==led_btn_xlslice_0_0} -quiet] -quiet

# IP: bd/led_btn/ip/led_btn_animation_0_0/led_btn_animation_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_btn_animation_0_0 || ORIG_REF_NAME==led_btn_animation_0_0} -quiet] -quiet

# IP: bd/led_btn/ip/led_btn_leds_spi_0_1/led_btn_leds_spi_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_btn_leds_spi_0_1 || ORIG_REF_NAME==led_btn_leds_spi_0_1} -quiet] -quiet

# IP: bd/led_btn/ip/led_btn_compteur_reset_0_0/led_btn_compteur_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_btn_compteur_reset_0_0 || ORIG_REF_NAME==led_btn_compteur_reset_0_0} -quiet] -quiet

# IP: bd/led_btn/ip/led_btn_axi_bram_ctrl_0_0/led_btn_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_btn_axi_bram_ctrl_0_0 || ORIG_REF_NAME==led_btn_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/led_btn/ip/led_btn_axi_smc_0/led_btn_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_btn_axi_smc_0 || ORIG_REF_NAME==led_btn_axi_smc_0} -quiet] -quiet

# IP: bd/led_btn/ip/led_btn_blk_mem_gen_0_1/led_btn_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_btn_blk_mem_gen_0_1 || ORIG_REF_NAME==led_btn_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/led_btn/ip/led_btn_c_addsub_0_0/led_btn_c_addsub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_btn_c_addsub_0_0 || ORIG_REF_NAME==led_btn_c_addsub_0_0} -quiet] -quiet

# IP: bd/led_btn/ip/led_btn_gnd_0/led_btn_gnd_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_btn_gnd_0 || ORIG_REF_NAME==led_btn_gnd_0} -quiet] -quiet

# IP: bd/led_btn/ip/led_btn_ila_0_1/led_btn_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_btn_ila_0_1 || ORIG_REF_NAME==led_btn_ila_0_1} -quiet] -quiet

# IP: bd/led_btn/ip/led_btn_xlconstant_0_0/led_btn_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_btn_xlconstant_0_0 || ORIG_REF_NAME==led_btn_xlconstant_0_0} -quiet] -quiet

# IP: bd/led_btn/ip/led_btn_top_level_0_0/led_btn_top_level_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_btn_top_level_0_0 || ORIG_REF_NAME==led_btn_top_level_0_0} -quiet] -quiet

# XDC: d:/Vivado/projet_led_spi/led_start/led_start.gen/sources_1/bd/led_btn/led_btn_ooc.xdc
